### PR TITLE
Ability to turn off direct font import in CSS

### LINKED ISSUE #45: Would it be possible to make the fonts in the themes optional?
I'm using Journal which has this font in `_overrides.scss`

```css
@import url(https://fonts.googleapis.com/css?family=News+Cycle:400,700);
```

But I also want to use this font that I include through my HTML.

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:200,300">
```

I would much rather **have them both be in the link tag** but News Cycle is hard coded into the overrides.

## Possible solutions:

Sass has control structures right? Can you add a boolean variable + an if-statement to conditionally include this font.

That way I can remove/disable it from my css and then combine it with Raleway in my link tag.

___

A simpler solution might be to add another scss file to the themes with custom fonts.

Add a `_theme-font.scss` file, it should contain just one line, the `@import url(...)`.

This allows me to do the same thing in a different way.

### PR DESCRIPTION
**Pull request by ghost**
Closes #45 

I named the variable `$bulmaswatch-import-font` so that its namespaced.

This solution only disables the hardcoded `@import`, it doesn't make the font configurable.

By disabling this, the user should know that they either need to import it through other means such as the `<link>` tag or override all instances of `font-family` manually.

**EDIT:**

PR #31 seems to try to solve the same problem but they only edited Flatly. I went through all the themes.

Their solution would be more ideal since it gives the user full control of the font, however they didn't put in the work to update all the themes.

Maybe you could implement it that way eventually, but for now I think this PR is a good enough solution to *some* of the problems caused by the hardcoded `@import`.

### CODE REVIEW

**Comment by jenil** [comment]
thanks @raniesantos

**Comment by ghost** [comment]
You're welcome, and thank you for merging!

**Comment by ghost** [comment]
@jenil I just want to know, do you wait for a certain amount of changes to be made before tagging a new version???

**Comment by jenil** [comment]
@raniesantos good question, I don't. I try to match it with the main Bulma project versioning. But if you'd like I can go ahead and push a patched patch version like `v0.7.1+2`. Unfortunately can't publish that on npm since it is not a valid semver.

**Comment by ghost** [comment]
I see, well if you can't publish to npm then I can't use it anyway.

**Comment by jenil** [comment]
you can just `npm install https://github.com/jenil/bulmaswatch`

**Comment by ghost** [comment]
Just a suggestion. I noticed that [Buefy](github.com/buefy/buefy) has recently stopped strictly adhering to Bulma's current version. They're on 0.6.7 which has Bulma 0.7.1 as a dependency.

I'm not just saying this because I'm waiting for my feature to get released, I just think that following Bulma's version is too restrictive.

It's also arguably unnecessary because *npm properly handles the dependencies anyway* depending on what Bulma version you specify in package.json.

Anyway, that's all, of course you still have the final decision in this.

**Comment by jenil** [comment]
I'm surely gonna stick to following bulma version considering ease of use. I'm happy to push a tag on changes :)

**Pull request merged**
