### PR TITLE
Update to Bulma v0.9.1

### PR DESCRIPTION
**Pull request by alqu**
Hi,

I updated all dependencies so far and ran `npm run build`. This is the result :-)

Thanks.

### CODE REVIEW

**Comment by elmatou** [comment]
Should solve #86 and others before bumping dependencies

**Comment by jenil** [comment]
@alqu thanks for this but unfortunately can't merge this directly. The upgrade is not as simple as running `npm run build`.

I am going to upgrade to `0.9.0`, publish that, and then upgrade `0.9.1`.

**Comment by alqu** [comment]
> @alqu thanks for this but unfortunately can't merge this directly. The upgrade is not as simple as running `npm run build`.
> 
> I am going to upgrade to `0.9.0`, publish that, and then upgrade `0.9.1`.

Thanks. I already noticed that updating dependencies are quite delicate. So I upgraded those that do not break the build chain. But obviously there is some more going on behind the scenes :-)

**Comment by erickhun** [comment]
@jenil wondering if you had any plan for upgrading? :)

**Pull request closed without merging**
