### PR TITLE
Use the variable $control-height to set height of form element.

### PR DESCRIPTION
**Pull request by deather**
Hi,

It may be more simple to use the variable $control-height instead of overwrite all form element.  It seems all were good after these changes.

If there is a problem, I will correct.

Thanks for reading

### CODE REVIEW

**Comment by jenil** [comment]
hey @deather 

Thanks for this.

The variable is the correct way to do this but the themes were made when it wasn't yet available.

Do you think you can add this to other themes also?

**Comment by deather** [comment]
Of course, I will spend some times tomorrow to add these changes

**Comment by deather** [comment]
Ok so I edited every override.sass and variables.sass file. I resume all the things below, when I write OK I encountered any problem for the theme.

- cerulean: :ok_hand: 
- cosmo: :ok_hand: 
- cyborg: Nothing to do
- darkly: :ok_hand: 
- flatly: :ok_hand: 
- journal: :ok_hand: 
- litera: :ok_hand: Also I uniformized the height of all element. Before `select` were a particular height. If it was necessary, I will rollback
- lumen: :ok_hand: I need a second check on this theme.
- lux: :ok_hand: 
- materia: :ok_hand: 
- minty: :ok_hand: 
- nuclear: Nothing to do
- pulse: :ok_hand: 
- sandstone: :ok_hand: 
- simplex: :ok_hand: 
- slate: :ok_hand: 
- solar: :ok_hand: 
- spacelab: Nothing to do
- superhero: Nothing to do
- united: :ok_hand: 
- yeti: :ok_hand: 

I think I say all the things, let me know if I have to do changes.

**Comment by jenil** [comment]
ok sweet. thanks for the PR @deather 

I'll check it out and merge soon! 👍

**Comment by deather** [comment]
Latest commit was here to check easily the issue #59

**Review by jenil — APPROVED** [review]

**Pull request merged**
